### PR TITLE
chore: 🤖 adds prettier

### PR DESCRIPTION
**Pull request by marcomafessolli**
## Add Prettier for Code Formatting

This PR adds Prettier as a dependency to the project's package and sets up a format script to format the code using Prettier's default rules. Additionally, a workflow file has been added to run Prettier on every merge to the main branch.

Working example: https://github.com/marcomafessolli/whatsapp-chatgpt/actions/runs/4215731993

### What's Changed

* Added Prettier as a dependency to the project's package.json
* Added a format script to the package.json that runs Prettier on all relevant files

### Why the Change Was Made

Code formatting consistency is important for code readability and maintainability. Prettier is a popular code formatter that helps ensure consistent formatting across a codebase. By adding Prettier as a dependency and setting up a format script, we can easily format the code according to Prettier's rules.

#### Additional Notes

This change also updates all files under with Prettier. No code changes were made.

### CODE REVIEW

**Comment by Zain-ul-din** [comment]
@marcomafessolli `prettier` is should be dependencies.

**Comment by marcomafessolli** [comment]
@Zain-ul-din updated!

**Comment by Zain-ul-din** [comment]
@marcomafessolli also add `.prettierrc` file and this config for now.

```
{
    "semi":            true,
    "tabWidth":         4,
    "printWidth":       100,
    "singleQuote":      true,
    "trailingComma":    "none",
    "jsxBracketSameLine": true,
    "bracketSameLine":    true,
    "endOfLine": "crlf"
}

```

**Review by Zain-ul-din — APPROVED** [review]

**Comment by Zain-ul-din** [comment]
Thanks!

**Pull request merged**
