### PR TITLE
feat: Add allow/block lists

### PR DESCRIPTION
**Pull request by jrojas-pena**

### CODE REVIEW

**Review by navopw — CHANGES_REQUESTED** [review]
Nice, can you add some documentation in the docs/ folder?

Then I will merge it.

And please run `npm run prettier`

**Comment by Seitk** [comment]
Hi @jrojas-pena I have a similar idea like you (especially when the transcription is ON)
I have also added a !config command to allow you to set the whitelist in runtime, you might consider to add that as well
https://github.com/Seitk/whatsapp-chatgpt/pull/2/files

**Comment by navopw** [comment]
@Seitk Can you please make a PR to the askrella/whatsapp-chatgpt repo?

I think the deny list is not necessary yet. We can add it later. Would confuse people.

**Comment by navopw** [comment]
Or maybe @jrojas-pena can remove deny list and resolve conflicts. Then I will merge this.

**Comment by Seitk** [comment]
okay let me submit a PR

**Comment by Seitk** [comment]
https://github.com/askrella/whatsapp-chatgpt/pull/144

**Pull request closed without merging**
