### PR TITLE
Added Dockerfile

### LINKED ISSUE #27: Available as a Docker Image?
It would be amazing if there were a Docker image and docker-compose file available for easy set for us less tech savvy!

### PR DESCRIPTION
**Pull request by RG7279805**
Resolves #27 
- added Dockerfile 
- added no sandbox for puputeer so that script can run inside docker image
- added docker build command in README.md

### CODE REVIEW

**Comment by connorv001** [comment]
Encouterd this issue while building. fixed it by replacing image :

```
[+] Building 0.7s (8/11)                                                                                                                                            
 => [internal] load build definition from Dockerfile                                                                                                           0.1s
 => => transferring dockerfile: 197B                                                                                                                           0.0s
 => [internal] load .dockerignore                                                                                                                              0.1s
 => => transferring context: 54B                                                                                                                               0.0s
 => [internal] load metadata for docker.io/library/node:latest                                                                                                 0.0s
 => [1/7] FROM docker.io/library/node                                                                                                                          0.1s
 => [internal] load build context                                                                                                                              0.1s
 => => transferring context: 249.96kB                                                                                                                          0.0s
 => [2/7] WORKDIR /tmp/app/                                                                                                                                    0.1s
 => [3/7] COPY . .                                                                                                                                             0.1s
 => ERROR [4/7] RUN npm install                                                                                                                                0.4s
------                                                                                                                                                              
 > [4/7] RUN npm install:
#0 0.405 /bin/sh: npm: not found
------
Dockerfile:7
--------------------
   5 |     COPY . .
   6 |     
   7 | >>> RUN npm install
   8 |     RUN npm install vite-node
   9 |     RUN apt-get update
--------------------
```

**Comment by wassef911** [comment]
@RG7279805 is it okay if I add some changes to the docker image? (reduce size/faster build)

**Comment by RG7279805** [comment]
@wassef911 sure go ahead let me know when done i would like to learn as well

**Comment by steve-hb** [comment]
Please remove chromium since the project migrated to HTTP calls

**Comment by RG7279805** [comment]
@steve-hb when did that happened 
last time i checked it was running a instance of WhatsApp web behind the scene
thats the reason i installed chromium here

**Comment by navopw** [comment]
I think whatsapp web is still using chromium since there is no good official whatsapp api.

Please let me know if this works and I will review and merge it!

Thank you everyone for contributing.

**Comment by RG7279805** [comment]
@navopw yes i have checked the image and it works nicely (only takes time to start the image)

**Pull request merged**
