### PR TITLE
fixes data.id.id.length by Update package.json

### PR DESCRIPTION
**Pull request by ShivamB25**
this.deviceType = data.id.id.length > 21 ? 'android' : data.id.id.substring(0, 2) == '3A' ? 'ios' : 'web'; ^
TypeError: data.id.id.substring is not a function
at Message._patch (/app/node_modules/whatsapp-web.js/src/structures/Message.js:91:75) at new Message (/app/node_modules/whatsapp-web.js/src/structures/Message.js:18:24) at Client.sendMessage (/app/node_modules/whatsapp-web.js/src/Client.js:699:16) at processTicksAndRejections (node:internal/process/task_queues:95:5)

### CODE REVIEW

**Comment by ShivamB25** [comment]
tested and checked with dockerFile. it works 👍

**Comment by ShivamB25** [comment]
related to this bug #229

**Comment by crypticatul** [comment]
Still not working. 

/home/ubuntu/whatsapp-chatgpt/node_modules/whatsapp-web.js/src/structures/Message.js:91
        this.deviceType = data.id.id.length > 21 ? 'android' : data.id.id.substring(0, 2) == '3A' ? 'ios' : 'web';
                                                                          ^

TypeError: data.id.id.substring is not a function
    at Message._patch (/home/ubuntu/whatsapp-chatgpt/node_modules/whatsapp-web.js/src/structures/Message.js:91:75)
    at new Message (/home/ubuntu/whatsapp-chatgpt/node_modules/whatsapp-web.js/src/structures/Message.js:18:24)
    at Client.sendMessage (/home/ubuntu/whatsapp-chatgpt/node_modules/whatsapp-web.js/src/Client.js:699:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by edgehub-cloud** [comment]
> Still not working.
> 
> /home/ubuntu/whatsapp-chatgpt/node_modules/whatsapp-web.js/src/structures/Message.js:91 this.deviceType = data.id.id.length > 21 ? 'android' : data.id.id.substring(0, 2) == '3A' ? 'ios' : 'web'; ^
> 
> TypeError: data.id.id.substring is not a function at Message._patch (/home/ubuntu/whatsapp-chatgpt/node_modules/whatsapp-web.js/src/structures/Message.js:91:75) at new Message (/home/ubuntu/whatsapp-chatgpt/node_modules/whatsapp-web.js/src/structures/Message.js:18:24) at Client.sendMessage (/home/ubuntu/whatsapp-chatgpt/node_modules/whatsapp-web.js/src/Client.js:699:16) at processTicksAndRejections (node:internal/process/task_queues:95:5)

I will have to check again because my current system is working fine

**Comment by edgehub-cloud** [comment]
Screenshot_2023-05-26-01-28-28-08_6012fa4d4ddec268fc5c7112cbb265e7
@crypticatul

**Comment by ShivamB25** [comment]
@crypticatul 
image

u will have to use this build image yourself if u want to use docker
```docker
version: "3"
services:
    whatsapp-chatgpt:
        build: .
        environment:
            OPENAI_API_KEY: "sk-"
            OPENAI_GPT_MODEL: ""
            PREFIX_ENABLED: "true"
            GROUPCHATS_ENABLED: "true"
            MAX_MODEL_TOKENS: 2000
            SERPAPI_API_KEY: ""
            TRANSCRIPTION_MODE: whisper-api
        volumes:
            - ./session-data:/app/session
volumes:
    session-data:```

**Comment by crypticatul** [comment]
Thanks 

> @crypticatul image
> 
> u will have to use this build image yourself if u want to use docker
> 
> ```
> version: "3"
> services:
>     whatsapp-chatgpt:
>         build: .
>         environment:
>             OPENAI_API_KEY: "sk-"
>             OPENAI_GPT_MODEL: ""
>             PREFIX_ENABLED: "true"
>             GROUPCHATS_ENABLED: "true"
>             MAX_MODEL_TOKENS: 2000
>             SERPAPI_API_KEY: ""
>             TRANSCRIPTION_MODE: whisper-api
>         volumes:
>             - ./session-data:/app/session
> volumes:
>     session-data:```
> ```


Thanks for the reply. I am getting the following error after sudo docker-compose up

docker-compose.yml', volume must be a mapping, not a string.

**Comment by VIRUS-ATTACK** [comment]
@ShivamB25, it is working for me too

**Comment by ShivamB25** [comment]
> @ShivamB25, it is working for me too

they should either merge my pr or update their dependencies

**Comment by crypticatul** [comment]
> sudo docker-compose up

Well, it is already merged. 
Pr-merged

However, I found the reason for the error, It was ``` after the session-data:

Anyways I am still having issues with the npm

**Comment by ShivamB25** [comment]
> > sudo docker-compose up
> 
> Well, it is already merged. Pr-merged
> 
> However, I found the reason for the error, It was ``` after the session-data:
> 
> Anyways, this worked for me ⬇️
> 
> https://github.com/pedroslopez/whatsapp-web.js/pull/2196/files

dunno man.  SHOULD i make a image myself lol. it is working on my system (i pulled latest from my own repo)

**Pull request merged**
