### PR TITLE
added `star-history`⭐ 📈

### PR DESCRIPTION
**Pull request by hemangjoshi37a**
added `star-history`⭐ 📈

### CODE REVIEW

**Comment by manishaarya9899359346** [comment]
Can I have ur nmb4

**Comment by manishaarya9899359346** [comment]
Help me out with this plZz

**Comment by navopw** [comment]
Hey @hemangjoshi37a 

we don't want to bloat the README file and keep it clean.

I have to decline your PR, still thanks for the contribution!

**Comment by navopw** [comment]
If its on the bottom of the README file its okay, I will accept.

**Comment by hemangjoshi37a** [comment]
@manishaarya9899359346 

my number is : +917016525813

**Pull request merged**
