### PR TITLE
feat: install necessary components in Dockerfile

### PR DESCRIPTION
**Pull request by law108000**
- whatsapp-web.js: install all components required for no-gui systems
- https://wwebjs.dev/guide/

### CODE REVIEW

**Comment by navopw** [comment]
Can you explain why we need aks-deployment.yml?

**Comment by EdEngineering** [comment]
Another volume you can create is a volume for the sessions, so if any error occurs you don't need to re scan the QR code to authenticate to the whatsapp session.

**Comment by EdEngineering** [comment]
> Can you explain why we need aks-deployment.yml?

I work deploying systems into prod, and kubernetes is a great solution, autoscalable, autohealing, lots of benefits really, so it is helpful to have those yaml files, i deployed this app myself in gke, with my own manifests.

**Comment by law108000** [comment]
> Can you explain why we need aks-deployment.yml?

Oh, I am sorry about that. It seems some code change on my fork project is being carried on to this accidentally.
actually, I would like to pull [bc183d5](https://github.com/askrella/whatsapp-chatgpt/pull/130/commits/bc183d548574bfc2246fcb718348cb15466ea1e3) only ... 

The other 4 commits are personal usage only (deployment with K8S into Azure). 
As @EdEngineering comments, that could be a useful example or template for others who would like to deploy this project into the cloud. 


> Another volume you can create is a volume for the sessions, so if any error occurs you don't need to re scan the QR code to authenticate to the whatsapp session, in the yaml manifest for k8s.

Thx @EdEngineering, you reminded me that I should add volume config into docker-compose too. So others could be skipping WhatsApp authentication every time they restarted the docker.

**Pull request closed without merging**
