### PR TITLE
feat: 🎸 turbos up cli

### PR DESCRIPTION
**Pull request by marcomafessolli**
Too much? 

https://user-images.githubusercontent.com/1048545/219962562-4b0a4d93-9d09-4bb1-9b3c-f66bd3b12044.mp4

<br/>
Closes: #59

### CODE REVIEW

**Comment by Zain-ul-din** [comment]
🔥🔥🔥 cool

**Review by Zain-ul-din — CHANGES_REQUESTED** [review]
@marcomafessolli please can you manage all spinner codes in `spinner.ts`  it will help us to manage code complexity.

**Comment by marcomafessolli** [comment]
@Zain-ul-din updated!

**Review by Zain-ul-din — CHANGES_REQUESTED** [review]
if you don't mind can you add all functions in one class so they can export as a single file.

Like:

```typescript
export class UiSpinner {
   public static printQRCode (qr:string) { }
}


```

**Comment by navopw** [comment]
I think thats fine for now, nice one <3

**Pull request merged**
